### ISSUE TITLE
我发现了一个问题和三个需求

### ISSUE THREAD

**Issue by ghost** [loliconer/vue-stackedit#6]
1、引用回车之后，新起一行，渲染的结果还是一行

2、如果能加上行号和:::info :::、:::error :::、:::success :::、:::warning :::标签会更有更多人使用吧

3、markdown和富文本编辑器相比，最大的不足就是操作table比较麻烦，如果能集成markdown-it-table插件就好了

**Comment by loliconer** [comment]
段落内换行需要在上一行末尾加两个空格，这是markdown的语法。
后面两个功能目前stackedit也没有支持，都需要使用插件实现，有时间研究一下。

其实我现在更喜欢所见即所得式的编辑器，比如语雀的编辑器，非常强大，可惜没有开源。主流的这种模式浪费了一半的屏幕。

**Comment by ghost** [comment]
可能我没有描述清楚---是在引用换行，渲染的结果还是一行，这估计是个bug吧，例如：
```markdown
>111
>222
>333
```
我期望的是一个引用包含三个段落，但是渲染的结果是包在一个p标签里啦
另外，就是后面不是两个问题，是三个问题。
我看了stackedit它是基于markdown-it插件渲染的对吧，markdown-it的插件库很多，markdown-it-container插件可以实现自定义块，能够实现:::info :::功能。
markdown-it-multimd-table插件可以实现对table的操作

对于行号我没发现

我是一个后端开发，最近刚学了一点vue还达不到开发的水平，所以只能提一点建议了

**Comment by loliconer** [comment]
感谢建议。
引用换行是类似的，都需要在行末尾加两个空格，我试了一下没问题。是在一个p标签里，里面会包含br标签。
如果需要多段落引用，可以新增一个空行
```
>111
>
>222
```

**Comment by ghost** [comment]
这样操作起来还是有些麻烦的 如果不是你给讲解 我真的还以为是bug呢

**Comment by loliconer** [comment]
MarkDown毕竟只是简单的文本编辑，要实现多种多样的排版效果，只能靠不同的写法来区分。
